# TEMPLATE: Search for the TEMPLATE keyword for sections that must be updated then remove the comment

# When creating a new branch, review all parameters making sure to:
#     - update useLockFile
#     - update defaultLockFileBranch
#     - update isRelease
#     - update demands (TVR_GREEN / TVR_WHITE)

# Parameters must remain in this file to be configurable at startup
parameters:
# Build agent selection
- name: pinHost
  displayName: Pin build to specific host (supply host below)
  type: boolean
  default: false
- name: pinnedHost
  displayName: Pinned Host
  type: string
  default: disabled
- name: debugMode
  displayName: Debug Mode
  type: boolean
  default: false
- name: clean
  displayName: Clean Build
  type: boolean
  default: false

# Embedded Package Repositories
- name: packageRepos
  displayName: Package Repositories
  type: object
  default:
    self: Simulation

# Packages Lock Management
- name: useLockFile
  displayName: Restore packages lock file from prior builds
  type: boolean
  # NOTE: This should be set to true for release branches
  default: false

- name: defaultLockFileBranch
  displayName: Default branch to retrieve lock file (for release branches this should be set to match, must enable lock file)
  type: string
  # NOTE: For release branches this should be set to match
  default: develop


trigger:
  batch: true
  branches:
    include:
    - develop
    - release*/**
  paths:
    exclude:
    - .azure
    - .github

pr: none


resources:
  repositories:
  # This repository should always be here and should not be defined in the repos parameter
  - repository: PipelineTemplates
    type: github
    endpoint: GITHUB_WRITE
    name: TRANSFR-Inc/PipelineTemplates
    ref: main

  # This repository should always be here and should be defined in the projectRepo parameter
  - repository: SDK_Project_Instance
    type: github
    endpoint: GITHUB_WRITE
    name: TRANSFR-Inc/SDK_Project_Instance
    ref: master

  # The source to restore the packages lock from when parameters.useLockFile is true
  pipelines:
  # NOTE: The initial build for a new pipeline will not succeed with this 
  # resource, make sure to un-comment it for subsequent builds
  - pipeline: LockFileSource
    # NOTE: This must match the current pipeline name
    source: <pipeline name> # TEMPLATE: Pipeline name (without path)
    branch: ${{ parameters.defaultLockFileBranch }}


variables:
- group: "Build_Pipeline"


extends:
  template: build-sim-template.yml@PipelineTemplates
  parameters:
    pinHost: ${{ parameters.pinHost }}
    pinnedHost: ${{ parameters.pinnedHost }}
    debugMode: ${{ parameters.debugMode }}
    clean: ${{ parameters.clean }}
    demands:                # TEMPLATE: Update demands
    # - TVR_SIM_<ZZZ>
    # - TVR_<GREEN|WHITE>
    packageRepos: ${{ parameters.packageRepos }}
    useLockFile: ${{ parameters.useLockFile }}
    productName:            # TEMPLATE: App Name
    scenes:                 # TEMPLATE: Asset path to scene(s) to include
    # - "Packages/com.transfrvr.<module>.<name>/<name>.unity"
    packageNamePrefix:      # TEMPLATE: com.transfrvr.<module>.<name>
    majorVersion:           # TEMPLATE: 0
    minorVersion:           # TEMPLATE: 0
    isRelease:              # TEMPLATE: false for qa / green / develop or true for rc / white / release
    buildQuest:             # TEMPLATE: true / false
    buildQuestOpenXR:       # TEMPLATE: true / false
    buildPico:              # TEMPLATE: true / false
    buildViveFocus:         # TEMPLATE: true / false
